<?php

/**
 * @file
 * Module implementation file.
 */

/**
 * Implement hook_help().
 */
function environment_indicator_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'admin/config/development/environment-indicator':
      return t('The Environment Indicator adds a coloured strip to the site informing you which environment you\'re currently in (Development, Staging Production etc). You may override these settings by adding a new environment based on the hostname being seen or with your settings.php file in each of your environments.');

    case 'admin/help#environment_indicator':
      $output = '<p>' .t('The Environment Indicator adds a coloured strip to the site informing you which environment you\'re currently in (Development, Staging Production etc') .'</p>';

      $output .= '<p>'. t('The Environment Indicator <a href="@settings">settings page</a> allows you to modify some elements of the indicator\'s behavior and appearance. Since the appearance of the indicator is dependent on your site theme, substantial customisations require modifications to your site\'s theme and CSS files.', ['@settings' => url('admin/config/development/environment-indicator')]) . '</p>';

      $output .= '<p>'. t('The Environment Indicator\'s visibility depends upon the permissions of the viewer. The <a href="@permissions">access environment indicator</a> permission must be enabled for a user role in order for users of that role to see the indicator.', ['@permissions' => url('admin/people/permissions', ['fragment' => 'module-environment_indicator'])]) .'</p>';

      $output .= '<p>'. t('The settings for the Environment Indicator, such as the text to display and the color can be overridden for each of your specific environments using the configuration UI or in the site\'s settings.php file. You can also export this configuration to code, this allows you to customise the indicator for each environment without needing to make any changes in the database. This means that the Environment Indicator will always display correctly when moving your site from development to staging to production. If you choose to detect your environment using settings.php, then all configuration variables can be overridden in settings.php, but the most common three are:') .'</p>';
      $output .= '<dl>';
      $output .= '<dt><em>environment_indicator_overwrite</em></dt><dd>'. t('A boolean value indicating whether the Environment Indicator should use the settings.php variables for the indicator. On your production environment, you should probably set this to FALSE.') . '<br/>$conf[\'environment_indicator_overwrite\'] = FALSE;<br />* ' . t('This setting corresponds to the old %setting in version 1.x.', ['%setting' => 'environment_indicator_enabled']) . '</dd></dt>';
      $output .= '<dt><em>environment_indicator_overwritten_name</em></dt><dd>'. t('The text that will be displayed on the indicator.') . '<br/>$conf[\'environment_indicator_overwritten_name\'] = \'Staging\';<br />* ' . t('This setting corresponds to the old %setting in version 1.x.', array('%setting' => 'environment_indicator_text')) . '</dd></dt>';
      $output .= '<dt><em>environment_indicator_overwritten_color</em></dt><dd>'. t('A valid css color.') . '<br/>$conf[\'environment_indicator_overwritten_color\'] = \'#F55\';<br />* ' . t('This setting corresponds to the old %setting in version 1.x.', array('%setting' => 'environment_indicator_color')) . '</dd></dt>';
      $output .= '<dt><em>environment_indicator_overwritten_position</em></dt><dd>'. t('Where your indicator may appear. Allowed values are "top" and "bottom".') . '<br/>$conf[\'environment_indicator_overwritten_position\'] = \'top\';</dd></dt>';
      $output .= '<dt><em>environment_indicator_overwritten_fixed</em></dt><dd>'. t('A boolean value indicating whether the Environment Indicator should be visible at all times, fixed at the top/bottom of the screen.') . '<br/>$conf[\'environment_indicator_overwritten_fixed\'] = FALSE;</dd></dt>';
      $output .= '</dl>';

      return $output;
  }
}


/**
 * Load function for menu loaders.
 */
function environment_indicator_load($name) {
  $controller = \Drupal::entityManager()->getStorage('environment_indicator');
  return $controller->load($name);
}

/**
 * Implements hook_page_build().
 */
function environment_indicator_page_attachments(&$page) {
  $page['#attached']['library'][] = 'environment_indicator/drupal.environment_indicator';
  if ($match = environment_indicator_get_active()) {
    if (environment_indicator_check_access($match)) {
      if (environment_indicator_needs_js()) {
$page['#attached']['drupalSettings']['environment_indicator']['toolbar-color'] = $match['color'];
        $page['#attached']['drupalSettings']['environment_indicator']['environment-indicator-name'] = [
          '#theme' => 'environment_indicator_indicator_name',
          '#name' => $match,
        ];
      }
      else if (!(\Drupal::moduleHandler()->moduleExists('admin_menu') && \Drupal::currentUser()->hasPermission('access administration menu'))) {
        environment_indicator_attach_indicator($match, $page);
      }
    }
  }
}

/**
 * Implements hook_theme().
 */
function environment_indicator_theme($existing, $type, $theme, $path) {
  return [
    'environment_indicator_indicator_name' => [
      'variables' => ['name' => NULL],
      'file' => 'environment_indicator.theme.inc',
    ],
    'environment_indicator_indicator_bar' => [
      'variables' => ['info' => NULL],
      'file' => 'environment_indicator.theme.inc',
    ],
    'environment_indicator_overritten_header' => [
      'file' => 'environment_indicator.theme.inc',
    ],
  ];
}

/**
 * Implements hook_admin_menu_output_alter().
 */
function environment_indicator_admin_menu_output_alter(&$content) {
  $environment_info = environment_indicator_get_active();
  if (!empty($environment_info)) {
    $content['environment_indicator'] = [
      '#theme' => 'html_tag',
      '#tag' => 'div',
      '#value' => [
        '#theme' => 'environment_indicator_indicator_name',
        '#name' => $environment_info,
      ],
      '#weight' => 50,
      '#attributes' => [
        'id' => 'environment-indicator',
        'style' => 'background-color: ' . $environment_info['color'],
      ],
    ];
  }
}

/**
 * Implements hook_toolbar().
 */
function environment_indicator_toolbar() {
  $environment = environment_indicator_get_active();
  $menu = _environment_indicator_switcher_menu();
  $items = array();

  $items['environment_indicator'] = [
    // Include the toolbar_tab_wrapper to style the link like a toolbar tab.
    // Exclude the theme wrapper if custom styling is desired.
    '#type' => 'toolbar_item',
    'tab' => [
      '#type' => 'link',
      '#theme' => 'user_message_toolbar_tab',
      '#title' => t('@name', ['@name' => $environment['label']]),
      '#href' => 'www.google.de',
      '#options' => [
        'attributes' => [
          'title' => t('Environments'),
          'class' => ['toolbar-icon', 'toolbar-icon-environment'],
        ],
      ],
    ],
    'tray' => $menu,
    '#weight' => -25,
  ];

  return $items;
}

/**
 * Helper function to attach the indicator to the page.
 */
function environment_indicator_attach_indicator($environment_info, &$page) {
  $page['page_' . $environment_info['position']]['environment_indicator'] = [
    '#theme' => 'environment_indicator_indicator_bar',
    '#info' => $environment_info,
  ];
}

/**
 * Helper function to get the active indicator.
 */
function environment_indicator_get_active() {
  $env = &drupal_static(__FUNCTION__);
  if (isset($env)) {
    return $env;
  }
  $environments = environment_indicator_get_all();
  $matches = array();
  foreach ($environments as $machine => $environment) {
    // Check if the environment record has ben disabled. Then check the regex.
    if (environment_indicator_match_path($environment->regexurl)) {
      $matches[] = [
        'label' => $environment->label,
        'id' => $environment->id,
        'weight' => $environment->weight,
        'color' => $environment->color,
        'position' => $environment->position,
        'fixed' => $environment->fixed,
      ];
    }
  }
  uasort($matches, array('Drupal\Component\Utility\SortArray', 'sortByWeightElement'));
  $env = reset($matches);
  return $env;
}

/**
 * Helper function to match the path based on the regular expression.
 *
 * @param string $regexurl
 *   The regular expression to match against.
 * @return int
 *   Indicating if the environment was a match.
 */
function environment_indicator_match_path($regexurl) {
  // If the URL includes a non-scaped slash then an error will be thrown.
  $regexurl = preg_replace("/([^\/])\//", "$1\/", $regexurl);
  return preg_match("/$regexurl/", $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI']);
}

/**
 * Helper function to get all environments.
 *
 * @param bool $fixed
 *   If TRUE it will only return fixed environments. Fixed environments are
 *   those that do not use a regular expression for detection.
 */
function environment_indicator_get_all($fixed = FALSE) {
  $environments = entity_load_multiple('environment_indicator');
  $environments = array_filter($environments, '_environment_indicator_active');
  // Check if the regular expression is a environment name.
  return $fixed ? array_filter($environments, '_environment_indicator_regex_filter') : $environments;
}

/**
 * Helper function to check access to show the indicator.
 *
 * @param array
 *   The environment info array.
 * @return boolean
 *   TRUE if the user can see the indicator.
 */
function environment_indicator_check_access($environment_info) {
  // Do not show the indicator on select pages.
  $supress_pages = \Drupal::config('environment_indicator.options')->get('suppress_pages');
  // Compare with the internal and path alias (if any).
  $current_path = \Drupal::request()->getRequestUri();
  $page_match = \Drupal::service('path.matcher')->matchPath($current_path, $supress_pages);
  if ($page_match) {
    return FALSE;
  }

  return \Drupal::currentUser()->hasPermission('access environment indicator') || \Drupal::currentUser()->hasPermission('access environment indicator ' . $environment_info['id']);
}

/**
 * Helper function to check if the JS needs to be included.
 *
 * @return boolean
 *   TRUE if the extra javascript is needed.
 */
function environment_indicator_needs_js() {
  return \Drupal::moduleHandler()->moduleExists('toolbar') && \Drupal::currentUser()->hasPermission('access toolbar');
}

/**
 * Filter callback
 */
function _environment_indicator_regex_filter($item) {
  return !preg_match("/[\*\?\[\]\(\)]/", $item->regexurl);
}

/**
 * Helper function to generate a menu with the environments to switch to.
 */
function _environment_indicator_switcher_menu() {
  $element = [
    '#heading' => t('Environment indicator'),
    'toolbar_indicators' => [
      '#type' => 'container',
      '#attributes' => [
        'class' => ['toolbar-menu-environment-indicator'],
      ],
      'indicator_menu' => [
        '#sorted' => TRUE,
        '#theme_wrappers' => ['menu_tree'],
      ],
    ],
  ];
  $environments = environment_indicator_get_all(TRUE);
  if (empty($environments)) {
    $element['toolbar_indicators']['indicator_menu']['empty'] = [
      '#theme' => 'menu_link',
      '#title' => '- ' . t('There are no other environments available.') . ' -',
      '#href' => \Drupal::request()->getRequestUri(),
      '#localized_options' => [
        'html' => TRUE,
      ],
      '#below' => [],
      '#attributes' => [
        'class' => ['leaf'],
      ],
    ];
  }
  $current_environment = environment_indicator_get_active();
  foreach ($environments as $id => $environment) {
    if ($id != $current_environment['id']) {
      $element['toolbar_indicators']['indicator_menu'][$environment->id()] = array(
        '#theme' => 'menu_link',
        '#title' => t('Open in: %name', array('%name' => $environment->label())),
        '#href' => 'http://' . $environment->get('regexurl') . '/' . \Drupal::request()->getRequestUri(),
        '#localized_options' => array(
          'html' => TRUE,
        ),
        '#below' => array(),
        '#attributes' => array(
          'class' => array('leaf'),
        ),
      );
    }
  }
  return $element;
}

/**
 * Filter callback
 */
function _environment_indicator_active($item) {
  // TODO: Implement an action for the configuration entity to disable it.
  return TRUE;
}
